### ISSUE TITLE
Support Softmax in nnj

### ISSUE THREAD

**Issue by sorenhauberg** [MachineLearningLifeScience/stochman#14]
We should also support Softmax() in nnj. Note to self: this is not an activation function per se, and the Jacobian won't be diagonal.

**Comment by sorenhauberg** [comment]
Something like this should work (here implemented in the 'old' geoml style, so some adaptation is needed)

`class Softmax(nn.Softmax):
    def forward(self, x, jacobian=False):
        val = torch.softmax(x, dim=self.dim)

        if jacobian:
            J, _ = self._jacobian(x, val)
            return val, J
        else:
            return val
    
    def _jacobian(self, x, val):
        J = torch.diag_embed(val) - torch.bmm(val.unsqueeze(-1), val.unsqueeze(-2))
        return J

    def _jac_mul(self, x, val, Jseq, JseqType):
        J = self._jacobian(x, val) # (B)x(in)x(in)
        if JseqType is JacType.FULL:
            Jseq = torch.bmm(J, Jseq)
            jac_type = JacType.FULL
            return Jseq, jac_type
        else:
            raise Exception('not implemented')`

**Comment by SkafteNicki** [comment]
Fixed in 14b7a3280314552ca3563c42b7c6571e276d6c02
